### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#26]
I've never done contributing style uploads before - normally I fork & branch like the two pulls you have thus far.  In order to pull your changes regularly & not blow out my other branches, I need to be a contributor on your project apparently, as it points the origin of my c9 at your repo.  As once you update the master branch - I'm potentially submitting dirty pulls.

If you're comfortable with me as contributor send me an invite.  

Otherwise I'll make the next pull request, wait for it to go through & check back in a few days from your accepting before I then delete the cloned repo & down load it fresh to github & repeat.

**Comment by jatwell93** [comment]
@Mirv i think i've added you as a collaborator now :)

**Comment by jatwell93** [comment]
Hey @Mirv i was making changes on the recipeVersion2 branch but cant commit them because of this error 
` To github.com:jatwell93/rubyproject.git
 ! [rejected]        recipeVersion2 -> recipeVersion2 (non-fast-forward)
error: failed to push some refs to 'git@github.com:jatwell93/rubyproject.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details. `

is the correct way to fix this ` git pull origin recipeVersion2 `? Then push? Sorry just dont want to screw up any of your code etc.

**Comment by Mirv** [comment]
I'm taking a peak at your c9 repo right now.

**Comment by Mirv** [comment]
Got it ... rather than trying to second guess why you did anything, after the 2nd hour pondering the git guts of the commits I decided to just accept your changes off `recipeVersion2`.

For you to resolve  your issues, you will need to 

1. git pull origin master

1. Open the file in question with conflicts off the list

1. Scroll to where it shows some highlighted code.  Here I can't guide you - you either need to select "use" on the code conflict.  Git will have added a comment after the line "ours" or the "theirs" version with the little buttons that show up.  

1. Do a 'git add <path/filename>' for each file changed.  You could do a 'git add -A', but that's really bad practice.

1. Do a 'git commit -m "<insert comment about the resolving of issue>".

Viola!  You are now up to date.

---

After this happens - always start a new branch before making changes.  Once it's ready & tested, add it & the tests back to the master by normal merge.  As long as you are regularly merging it will always accept your changes - its when you get two changes away from the branch that it will start rejecting & call for merges in conflicts.

**Comment by jatwell93** [comment]
You're amazing, thanks so much for all that info i feel like i'm starting to finally understand git. i followed those commands and everything seems to be working again! I started panicking thinking i managed to wreck all your hard work hahaha. AAlright from now on ill following your example on the other issue.

**Comment by Mirv** [comment]
Thanks - I'm really not that great with git either - but seriously - once it's committed unless you rebase or squash commit's it's always there!
